// Navigation is editorial UI copy. Prompt titles and bodies come only from CMS.
const rows = {
  en: [
    "Browse by category",
    "Browse by model",
    "Latest examples",
    "Complete catalog",
    "Examples",
    "Start here",
    "Reference images",
    "Reference images required — open the detail page for the source context.",
    "Original prompt",
    "Remix of",
    "Source excerpt is partial.",
    "Source code",
    "Build brief based on the linked work",
  ],
  zh: [
    "按用途浏览",
    "按模型浏览",
    "最新案例",
    "完整目录",
    "案例",
    "开始使用",
    "参考图片",
    "此案例需要参考图片，请打开详情页查看来源上下文。",
    "作者原始提示词",
    "改编自",
    "来源摘录不完整。",
    "项目源码",
    "基于原作品整理的创作说明",
  ],
  "zh-Hant": [
    "依用途瀏覽",
    "依模型瀏覽",
    "最新案例",
    "完整目錄",
    "案例",
    "開始使用",
    "參考圖片",
    "此案例需要參考圖片，請開啟詳情頁查看來源上下文。",
    "作者原始提示詞",
    "改編自",
    "來源摘錄不完整。",
    "專案原始碼",
    "根據原作品整理的創作說明",
  ],
  ja: [
    "カテゴリで探す",
    "モデルで探す",
    "最新の作例",
    "全カタログ",
    "作例",
    "はじめに",
    "参照画像",
    "参照画像が必要です。詳細ページで確認してください。",
    "作者の元のプロンプト",
    "リミックス元",
    "出典は部分的な抜粋です。",
    "ソースコード",
    "出典の作品を基にした制作指示",
  ],
  ko: [
    "카테고리별 탐색",
    "모델별 탐색",
    "최신 사례",
    "전체 카탈로그",
    "사례",
    "시작하기",
    "참고 이미지",
    "참고 이미지가 필요합니다. 상세 페이지를 확인하세요.",
    "작성자의 원본 프롬프트",
    "리믹스 원작",
    "출처의 일부만 발췌되었습니다.",
    "소스 코드",
    "원작을 바탕으로 정리한 제작 지침",
  ],
  es: [
    "Explorar por categoría",
    "Explorar por modelo",
    "Últimos ejemplos",
    "Catálogo completo",
    "Ejemplos",
    "Primeros pasos",
    "Imágenes de referencia",
    "Se requieren imágenes de referencia; consulta la página del ejemplo.",
    "Prompt original",
    "Remix de",
    "El extracto de la fuente es parcial.",
    "Código fuente",
    "Instrucciones basadas en la obra enlazada",
  ],
  pt: [
    "Explorar por categoria",
    "Explorar por modelo",
    "Exemplos recentes",
    "Catálogo completo",
    "Exemplos",
    "Comece aqui",
    "Imagens de referência",
    "Imagens de referência necessárias; consulte a página do exemplo.",
    "Prompt original",
    "Remix de",
    "O trecho da fonte é parcial.",
    "Código-fonte",
    "Instruções baseadas na obra vinculada",
  ],
  de: [
    "Nach Kategorie",
    "Nach Modell",
    "Neueste Beispiele",
    "Vollständiger Katalog",
    "Beispiele",
    "Erste Schritte",
    "Referenzbilder",
    "Referenzbilder erforderlich; siehe Detailseite.",
    "Original-Prompt",
    "Remix von",
    "Die Quelle ist nur teilweise enthalten.",
    "Quellcode",
    "Arbeitsanweisung auf Grundlage des verlinkten Werks",
  ],
  fr: [
    "Par catégorie",
    "Par modèle",
    "Derniers exemples",
    "Catalogue complet",
    "Exemples",
    "Pour commencer",
    "Images de référence",
    "Images de référence requises ; consultez la page du projet.",
    "Prompt original",
    "Remix de",
    "La source est un extrait partiel.",
    "Code source",
    "Consignes fondées sur l’œuvre liée",
  ],
  it: [
    "Per categoria",
    "Per modello",
    "Ultimi esempi",
    "Catalogo completo",
    "Esempi",
    "Inizia qui",
    "Immagini di riferimento",
    "Sono necessarie immagini di riferimento; consulta la pagina del progetto.",
    "Prompt originale",
    "Remix di",
    "La fonte è un estratto parziale.",
    "Codice sorgente",
    "Istruzioni basate sull’opera collegata",
  ],
  ru: [
    "По категориям",
    "По моделям",
    "Новые примеры",
    "Полный каталог",
    "Примеры",
    "С чего начать",
    "Референсы",
    "Нужны референсы — откройте страницу примера.",
    "Исходный промпт автора",
    "Ремикс работы",
    "Источник приведён частично.",
    "Исходный код",
    "Техническое задание на основе работы по ссылке",
  ],
  tr: [
    "Kategoriye göre",
    "Modele göre",
    "Yeni örnekler",
    "Tam katalog",
    "Örnekler",
    "Başlangıç",
    "Referans görseller",
    "Referans görseller gerekli; ayrıntı sayfasını açın.",
    "Özgün istem",
    "Uyarlama kaynağı",
    "Kaynak alıntısı eksiktir.",
    "Kaynak kodu",
    "Bağlantıdaki çalışmaya dayalı yapım yönergesi",
  ],
  uk: [
    "За категоріями",
    "За моделями",
    "Нові приклади",
    "Повний каталог",
    "Приклади",
    "Початок роботи",
    "Референси",
    "Потрібні референси — відкрийте сторінку прикладу.",
    "Оригінальний промпт автора",
    "Ремікс роботи",
    "Джерело наведено частково.",
    "Вихідний код",
    "Технічне завдання на основі роботи за посиланням",
  ],
  vi: [
    "Theo danh mục",
    "Theo mô hình",
    "Ví dụ mới nhất",
    "Danh mục đầy đủ",
    "Ví dụ",
    "Bắt đầu",
    "Ảnh tham chiếu",
    "Cần ảnh tham chiếu; hãy mở trang chi tiết.",
    "Prompt gốc",
    "Phỏng theo",
    "Nguồn chỉ được trích một phần.",
    "Mã nguồn",
    "Hướng dẫn dựng dựa trên tác phẩm được liên kết",
  ],
};
export const ui = (locale) =>
  Object.fromEntries(
    [
      "categories",
      "models",
      "latest",
      "catalog",
      "examples",
      "start",
      "references",
      "required",
      "original",
      "remix",
      "partial",
      "code",
      "derived",
    ].map((key, i) => [key, rows[locale.code][i]]),
  );
